insert into department.groups (group_id, group_name) values (1, 'uf-57');
insert into department.groups (group_id, group_name) values (2, 'zl-01');
insert into department.students (student_id, group_id, last_name, first_name) values (1, 1, 'Smith', 'Oliver');
insert into department.students (student_id, group_id, last_name, first_name) values (2, 1, 'Gonzales', 'Lucas');
insert into department.students (student_id, group_id, last_name, first_name) values (3, 1, 'Wilson', 'Mary');
insert into department.students (student_id, group_id, last_name, first_name) values (4, 2, 'Anderson', 'Linda');
insert into department.students (student_id, group_id, last_name, first_name) values (5, 2, 'Harris', 'James');
insert into department.students (student_id, last_name, first_name) values (6, 'Thomas', 'Henry');
insert into department.courses (course_id, course_name) values (1, 'Math');
insert into department.courses (course_id, course_name) values (2, 'Programming');
